// components/buttons/UserMenu.tsx
/* eslint-disable @typescript-eslint/restrict-template-expressions */
'use client'

import { UserIcon } from '@/icons'
import { Menu, Transition } from '@headlessui/react'
import { Fragment, useState } from 'react'
import { AboutMe, ContactMe, Resume } from '../views'

export const UserMenu = (): React.ReactNode => {
  const menuItems = [
    { title: 'About me', code: 'about-me' },
    { title: 'Resume', code: 'resume' },
    { title: 'Contact me', code: 'contact-me' }
  ]

  const [view, setView] = useState<string | null>(null)

  const onChangeView = (code: string): void => setView(code)
  const onResetView = (): void => setView(null)

  return (
    <>
      <Menu as='div' className='relative inline-block text-left'>
        <Menu.Button aria-label='menu' className='group flex justify-center p-3 bg-button-bg rounded-2xl shadow-btn transition-colors hover:bg-button-hover aria-expanded:bg-button-hover'>
          <UserIcon style='h-7 w-7 fill-text-secondary transition-colors group-hover:fill-text-hover group-aria-expanded:fill-text-hover' />
        </Menu.Button>

        <Transition
          as={Fragment}
          enter='transition ease-out duration-150'
          enterFrom='transform opacity-0 scale-95'
          enterTo='transform opacity-100 scale-100'
          leave='transition ease-in duration-100'
          leaveFrom='transform opacity-100 scale-100'
          leaveTo='transform opacity-0 scale-95'
        >
          <Menu.Items className='absolute end-0 lg:end-15 top-15 lg:top-0 z-50 mt-0 w-60 origin-top-rigth bg-component-bg rounded-md shadow-btn focus:outline-none'>
            <div className='divide-y divide-component-divider'>
              <h3 className='text-lg text-text-main font-medium px-5 py-4 select-none'>
                Rafael Carvacho <span className='text-text-focus font-normal'>#WEB</span>
              </h3>
              <div className='flex flex-col gap-3 p-5'>
                {menuItems.map((item, index) => (
                  <Menu.Item as='div' key={index}>
                    <button onClick={() => onChangeView(item.code)} className='px-3 py-1 w-full rounded-md text-lg text-start text-text-secondary cursor-pointer transition-colors hover:text-text-hover hover:bg-component-hover'>
                      {item.title}
                    </button>
                  </Menu.Item>
                ))}
              </div>
            </div>
          </Menu.Items>
        </Transition>
      </Menu>

      {view === 'about-me' && <AboutMe onResetView={onResetView} />}
      {view === 'resume' && <Resume onResetView={onResetView} />}
      {view === 'contact-me' && <ContactMe onResetView={onResetView} />}
    </>
  )
}

// src/islands/dropdown/UserMenu.svelte
<script>
  import UserIcon from "./UserIcon.svelte";
  import AboutMe from "../modal/AboutMe.svelte";
  import Resume from "../modal/Resume.svelte";
  import ContactMe from "../modal/ContactMe.svelte";

  let isMenuOpen = false;
  let container;

  const handleMenu = () => {
    isMenuOpen = !isMenuOpen
  }
  function onWindowClick(e) {
    if (container.contains(e.target) === false) isMenuOpen = false
  }
</script>

<svelte:window on:click={onWindowClick} />

<div bind:this={container} class="relative inline-block text-left">
  <button on:click={handleMenu} aria-label="menu" class={`group flex justify-center p-3 bg-bg-btn rounded-2xl shadow-btn transition-colors hover:bg-hover-btn ${isMenuOpen ? "bg-hover-btn": ""}`}>
    <UserIcon style={`h-7 w-7 transition-colors group-hover:fill-hover-text ${isMenuOpen ? "fill-hover-text" : "fill-text-secondary"}`} />
  </button>
  {#if isMenuOpen}
    <section
      class="absolute end-0 lg:end-15 top-15 lg:top-0 z-50 mt-0 w-60 origin-top-rigth bg-bg-component rounded-md shadow-btn focus:outline-none"
    >
      <div class="divide-y divide-divider-component">
        <h3 class="text-lg text-text-primary font-medium px-5 py-4 select-none">
          Rafael Carvacho <span class="text-text-active">#WEB</span>
        </h3>
        <ul class="flex flex-col gap-3 p-5">
          <li> <AboutMe /> </li>
          <li> <Resume /> </li>
          <li> <ContactMe /> </li>
        </ul>
      </div>
    </section>
  {/if}
</div>
