// components/views/Resume.tsx
'use client'

import resumeList from '@/public/resumeList.json'
import { useEffect, useState } from 'react'
import { Modal } from './Modal'
import { ResumeList } from '../resumen'

export const Resume = ({ onResetView }: { onResetView: () => void }): React.ReactNode => {
  const [isOpen, setIsOpen] = useState(false)

  useEffect(() => {
    setIsOpen(true)
  }, [])

  const onClose = (): void => {
    setIsOpen(false)
    setTimeout(() => {
      onResetView()
    }, 200)
  }

  return (
    <Modal isOpen={isOpen} onClose={onClose}>
      <h2 className='text-4xl font-medium text-center md:text-start'>Work & Education</h2>
      <div className='flex items-center mt-8 min-h-[50vh]'>
        <div className='flex justify-between gap-8'>
          <ResumeList
            items={resumeList.filter(item => item.code === 'work')}
            style='hidden md:block md:max-w-[47%]'
          />
          <ResumeList
            items={resumeList.filter(item => item.code === 'education')}
            style='hidden md:block md:max-w-[47%]'
          />
          <ResumeList
            items={resumeList}
            style='block md:hidden'
          />
        </div>
      </div>
    </Modal>
  )
}

// src/islands/modal/Resume.svelte
<script>
  import data from "../../assets/resumeData.json";
  import Modal from "./Modal.svelte";
  import ResumeList from "../resume/ResumeList.svelte";

  let showModal = false;
</script>

<button
  on:click={() => (showModal = true)}
  class="px-3 py-1 w-full rounded-md text-lg text-start text-text-secondary cursor-pointer transition-colors hover:text-hover-text hover:bg-hover-component"
>
  Resumen
</button>

<Modal bind:showModal title="Trabajo & Educación">
  <section class="flex items-center mt-8 min-h-[50vh]">
    <div class="flex justify-between gap-8">
      <ResumeList
        items={data.filter(item => item.code === "work")}
        style="hidden md:block md:max-w-[47%]"
      />
      <ResumeList
        items={data.filter(item => item.code === "education")}
        style="hidden md:block md:max-w-[47%]"
      />
      <ResumeList
        items={data}
        style="block md:hidden"
      />
    </div>
  </section>
</Modal>
